test compile

target x86_64

function u0:5(i64, i64, i64) system_v {
    ss0 = explicit_slot 0
    ss1 = explicit_slot 8
    ss2 = explicit_slot 8
    ss3 = explicit_slot 8
    ss4 = explicit_slot 8
    ss5 = explicit_slot 1

ebb0(v0: i64, v1: i64, v2: i64):
    v3 = stack_addr.i64 ss1
    store v1, v3
    v4 = stack_addr.i64 ss2
    store v2, v4
    v5 = stack_addr.i64 ss3
    v6 = stack_addr.i64 ss4
    v7 = stack_addr.i64 ss5
    jump ebb1

ebb1:
; StorageLive(_3)
    nop 
; _3 = _1
    v8 = load.i64 v3
    store v8, v5
; StorageLive(_4)
    nop 
; _4 = _2
    v9 = load.i64 v4
    store v9, v6
; _5 = Eq(_4, const 0u64)
    v10 = load.i64 v6
    v11 = iconst.i64 0
    v12 = icmp eq v10, v11
    v13 = bint.i8 v12
    store v13, v7
    v14 = load.i8 v7
; 
; assert(!move _5, "attempt to divide by zero")
    brnz v14, ebb2
    trap user65535

ebb2:
; _0 = Div(move _3, move _4)
    v15 = load.i64 v5
    v16 = load.i64 v6
    v17 = udiv v15, v16
    store v17, v0
; StorageDead(_4)
    nop 
; StorageDead(_3)
    nop 
; 
; return
    return
}
